### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ProfM2** [stwe/DtBundleDemo#3]
I had to use the following to get this demo up and running:

1)  git clone https://github.com/stwe/DtBundleDemo.git
2)  cd into DtBundleDemo
3)  composer install
     NOTE: composer install ALSO creates the parameters.yml for the database/database user ...
4)  in your database, create a user (I called mine dtdemo), along with the database ... same as above
5)  php bin/console assets:install --symlink
6)  php bin/console fos:js-routing:dump
7)  php bin/console doctrine:schema:create
8)  php bin/console doctrine:fixtures:load --no-interaction

At this point, you should be able to run the server ... php bin/console server:run

**Comment by stwe** [comment]
and what is the problem ?

**Comment by ProfM2** [comment]
You have a few less steps necessary to get this up and running.  Someone newer to Symfony/Composer would have a little bit harder time trying to get it up and running.
